---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.dekorate.io/commit-id: "<<unknown>>"
    app.dekorate.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-gateway"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-gateway"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "<<unknown>>"
    app.dekorate.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-gateway"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-gateway"
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: "demo-gateway"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  annotations:
    app.dekorate.io/commit-id: "<<unknown>>"
    app.dekorate.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-gateway"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-gateway:view"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "view"
subjects:
- kind: "ServiceAccount"
  name: "demo-gateway"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.dekorate.io/commit-id: "<<unknown>>"
    app.dekorate.io/vcs-url: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-gateway"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "demo-gateway"
      app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.dekorate.io/commit-id: "<<unknown>>"
        app.dekorate.io/vcs-url: "<<unknown>>"
      labels:
        app.kubernetes.io/name: "demo-gateway"
        app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        image: "fsalikutluk/demo-gateway:0.0.1-SNAPSHOT"
        imagePullPolicy: "IfNotPresent"
        name: "demo-gateway"
      serviceAccount: "demo-gateway"
